include current-theme.conf

disable_ligatures always
enable_audio_bell no
enabled_layouts vertical, horizontal, stack
font_family Iosevka Nerd Font
font_size 12
scrollback_lines 10000
# Shell integration is sourced and configured manually
shell_integration no-rc
update_check_interval 0
window_padding_width 2

# passthru
map ctrl+alt+/ send_text all \x1b[47;7u
map ctrl+alt+0 send_text all \x1b[48;7u
map ctrl+alt+1 send_text all \x1b[49;7u
map ctrl+alt+2 send_text all \x1b[50;7u
map ctrl+alt+3 send_text all \x1b[51;7u
map ctrl+alt+4 send_text all \x1b[52;7u
map ctrl+alt+5 send_text all \x1b[53;7u
map ctrl+alt+6 send_text all \x1b[54;7u
map ctrl+alt+7 send_text all \x1b[55;7u
map ctrl+alt+8 send_text all \x1b[56;7u
map ctrl+alt+9 send_text all \x1b[57;7u
map ctrl+alt+enter send_text all \x1b[13;7u
map ctrl+alt+minus send_text all \x1b[45;7u
map ctrl+shift+tab send_text all \x1b[9;6u
map ctrl+tab send_text all \x1b[9;5u
map shift+enter send_text all \x1b[13;2u

map kitty_mod+minus change_font_size all -1.0
map kitty_mod+plus change_font_size all +1.0
map kitty_mod+enter launch --type=tab --tab-title=current --location=after --cwd=current
map kitty_mod+' launch --location=hsplit
map kitty_mod+b launch --allow-remote-control kitty +kitten broadcast --match-tab state:focused
map kitty_mod+e neighboring_window down
map kitty_mod+i neighboring_window up
map kitty_mod+f toggle_layout stack
